### ISSUE TITLE
running GXLE under Slurm instead of LSF

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#2]
Hi,
To run the GXLE code we only have a HPC environment with SLURM as workload manager and Amber as a module loaded in that computing environment. We wonder whether you could guide us to the proper GXLE script files we can modify or delete in order to avoid both the bsub instructions and Amber environmental variables containing in the GXLE code.
Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
You can try:

For Amber environmental variables:
1. In your "./bashrc", add a line "AMBERHOME=your Amber path"

For bsub:
2. Annotate or delete additional content from the “.bsub” file, leaving only the command line. Leave blank lines when deleting content.
For example, leave only "$AMBERHOME/bin/pmemd.cuda -O -i wat_min1.in -o 2cet_wat_min1.log -c 2cet_solv.inpcrd -p 2cet_solv.prmtop -r 2cet_wat_min1.rst -ref 2cet_solv.inpcrd" in file "amber18-gpu.bsub" in line 45.
3. Change ".bsub" to ".sh"

For content in scripts "run_tleap_min1.sh" "run_min2.sh" and "run_gbsa.sh"
4. Annotate or remove the function section related to “jobname”. 
For example, change
       "while true;do
		jobsnum=$(bjobs | grep PEND | wc -l)
		if [[ $jobsnum -gt 6 ]];then
			#echo "Waiting due to job in PEND more than 10"
			sleep 50
			continue
		else
			bsub < amber18-gpu.bsub
			break
		fi
	done"
to 
       "while true;do
			bsub < amber18-gpu.bsub
			break
	done"
5. Replace "bsub <" in the scripts with "sh". And replace ". bsub" in the scripts with “. sh ".

**Comment by mglgc** [comment]
Thank you for your instructions. Please, could you elaborate a bit more the step #5? Just one example would be enough clear for me.
Anyway, after all such a modifications as described, we have unsuccessfully runned GXLE and some error lines are showed. Starting to run the GXLE.sh script from the GXLE main directory, I'm including only the first three error lines (most relevants I guess):

cp: cannot stat '../setup/*_complex.pdb': No such file or directory
cp: cannot stat '../setup/*_ligand.mol2_1': No such file or directory
cp: cannot stat '../setup/*_ligand.frcmod': No such file or directory

Previously, I have changed all ".bsub" ocurrences to ".sh" and "source ~/.cshrc" to "~/.bashrc" in the main-setup.sh file.

**Comment by mglgc** [comment]
Thank you for your instructions. Please, could you elaborate a bit more the step #5? Just one example would be enough clear for me.
Anyway, after all such a modifications as described, we have unsuccessfully runned GXLE and some error lines are showed. I'm including only the first ones (most relevants I guess)::
---------------------------------
/etc/profile.d/zz-cesga.sh: line 59: syntax error near unexpected token `<'
/etc/profile.d/zz-cesga.sh: line 59: `	done < <(ldapsearch -LLL -x -b "uid=$LOGNAME,ou=usershpc,ou=users,dc=cesga,dc=es" '(objectClass=posixAccount)' description | egrep '^ |^description')'
/etc/profile.d/zz-motd.sh: line 66: syntax error near unexpected token `<'
/etc/profile.d/zz-motd.sh: line 66: `		done < <(ldapsearch -LLL -x -b "uid=$LOGNAME,ou=usershpc,ou=users,dc=cesga,dc=es" '(objectClass=posixAccount)' description | egrep '^ |^description')'
/etc/profile.d/zz-cesga.sh: line 59: syntax error near unexpected token `<'
/etc/profile.d/zz-cesga.sh: line 59: `	done < <(ldapsearch -LLL -x -b "uid=$LOGNAME,ou=usershpc,ou=users,dc=cesga,dc=es" '(objectClass=posixAccount)' description | egrep '^ |^description')'
/etc/profile.d/zz-motd.sh: line 66: syntax error near unexpected token `<'
/etc/profile.d/zz-motd.sh: line 66: `		done < <(ldapsearch -LLL -x -b "uid=$LOGNAME,ou=usershpc,ou=users,dc=cesga,dc=es" '(objectClass=posixAccount)' description | egrep '^ |^description')'
-------------------------------
For some reason I don't know the GXLE are reading those local system files. Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Step5, for content in scripts "run_tleap_min1.sh" "run_min2.sh" and "run_gbsa.sh", replace "bsub <" in the scripts with "sh". And replace ". bsub" in the scripts with “. sh ".
For example, line 81 in "run_tleap_min1.sh" 
change "bsub < amber18-gpu.bsub" to "sh amber18-gpu.sh"

**Comment by mglgc** [comment]
Hi,
Thank you for your reply. After that I'm running GXLE but at last some execution errors are found with the scripts run_min2.sh and run_tleap_min1.sh containing lines refering bsub:
sed -i "6c\#BSUB -J AMber-${1}" amber18-min2.sh

Please, could you provide us with the proper fix? Once again thank you very much in advance for you reply.

**Comment by LinaDongXMU** [comment]
Hi,
You can try to delete this line and change 45c to 1c in the next line. 
I have written examples of each file replacement and placed them in the Default-EmberEnv under main of GXLE. 
I hope this is helpful.

**Comment by mglgc** [comment]
Thank you very much for all your effort. We have used those example files as indicated.

After GXLE is started and running, the "run_gbsa.sh" script shows at line 31 an error message calling "ante-MMPBSA.py" python script that is missing in your GXLE distribution. Please, could you seed some light on this issue?
Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
ante-MMPBSA.py is an AMBER built-in script that requires the correct configuration of the environment. For detailed information, please refer to the AMBER manual.

**Comment by mglgc** [comment]
> Hi, ante-MMPBSA.py is an AMBER built-in script that requires the correct configuration of the environment. For detailed information, please refer to the AMBER manual.

Thank you very much for your explanation.
