### ISSUE TITLE
Amber parameter errors about WAT atom types

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#3]
Hi,
The GXLE code is unsuccessfully ending with teLeap errors about all O and H atoms from the WAT residues containing in the *_solv.pdb files. Cheking the leap.log file you can find lot of line errors as these ones:

amber/20.13-AmberTools-22.2/bin/teLeap: Error!
For atom (.R<WAT 20082>.A<O 1>) could not find vdW (or other) parameters for type (OW)

amber/20.13-AmberTools-22.2/bin/teLeap: Error!
For atom (.R<WAT 20082>.A<H1 2>) could not find vdW (or other) parameters for type (HW)

Please, could you figure out what the issue is? Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
Please delete the row containing water molecules (WAT) in the input _protein.pdb file at first.

**Comment by LinaDongXMU** [comment]
I have updated the script main-setup.sh in Default-AmberEnv.
Now line 25 have the function of deleting WAT from _protein.pdb file. 
I hope this is helpful.

**Comment by mglgc** [comment]
> I have updated the script main-setup.sh in Default-AmberEnv. Now line 25 have the function of deleting WAT from _protein.pdb file. I hope this is helpful.

Thank you very much for your fix.
