### ISSUE TITLE
.rst and _solv.inpcrd files are not found

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#4]
Hi,
Using your .sh scripts from Default-AmberEnv and you example data, the tleap running is OK but both amber18-gpu.sh and amber18-min2.sh scripts show the following errors:

Unit    9 Error on OPEN: 1bcu_solv.inpcrd
Unit    9 Error on OPEN: 1bcu_wat_min1.rst

because the *.rst and *_solv.inpcrd files are not building by the GXLE code. Please. could you give us some clues to fix it?
Once again thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
Check files after tleap. Have you gotten 1bcu_solv.inpcrd? If not, these errors are from tleap.

**Comment by mglgc** [comment]
Thank you very much for your reply. I could fix the tleap running.
