### ISSUE TITLE
2fvd_ligand molecule error

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#5]
Hi,
As you know, the 'run_tleap_min1.sh' script contain some tleap settings for a molecule labelled as "2fvd". Running GXLE using the example data one error about that molecule is showed in the leap.log file as follows:

> PRL = loadmol2 1bcu_ligand.mol2_1
Loading Mol2 file: ./1bcu_ligand.mol2_1
Reading MOLECULE named PRL
> loadamberparams 1bcu_ligand.frcmod
Loading parameters: ./1bcu_ligand.frcmod
Reading force field modification type file (frcmod)
Reading title:
Remark line goes here
> loadamberparams 2fvd_ligand.frcmod
software/MPI/gcc/system/openmpi/4.0.5_ft3_cuda/amber/20.13-AmberTools-22.2/bin/teLeap: Fatal Error!
Could not open file 2fvd_ligand.frcmod: not found

What and where is "2fvd_ligand"?
Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
Check your line 43 in run_tleap_min1.sh.
The "run_tleap_min1.sh" in DefaultAmberEnv, line 43 is "sed -i "4c\loadamberparams ${pdbid}_ligand.frcmod" tleap.in".
If it is right, it won't happen as "loadamberparams 2fvd_ligand.frcmod".
It should be "loadamberparams 1bcu_ligand.frcmod" as example.

**Comment by mglgc** [comment]
Hi,
Thank you for your reply. I have just figured out why this error was happend. I have added the line "source leaprc.water.tip3p" to the run_tleap_min1.sh script in order to avoid the leap error about the WAT residues in the *_solv.pdb files, but I haven't fixed accordingly all the 'sed' lines including in the sh script.
Thank you very much once again for your replies..
