### ISSUE TITLE
Floating-point warnings running GXLE

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#6]
Hi,
We're running the example data for 20 hours so far and thousand of warning lines are persistently displaying about floating-point exceptions:
"Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG"
Please, some remarks about that behaviour will be of helpful guide to go ahead. Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Hi,
This issue is from Linux system, not from the scripts. Change the default version of gcc (downgrade/upgrade of gcc version).

**Comment by mglgc** [comment]
OK. Thank you very much for your promptly reply.
