### ISSUE TITLE
Incompatibility error for model in GXLE.py

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/GXLE#7]
The version of scikit-learn for which the GXLE.pkl model was built seems not to be the 0.24.1version installed under the GXLE conda environment, so the GXLE.py script does not work showing the following error lines:

python3.9/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator ExtraTreeRegressor from version 0.24.1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "GXLE/application/for_model/GXLE.py", line 22, in <module>
    estimator=joblib.load("./GXLE.pkl")
  File "python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "python3.9/site-packages/joblib/numpy_pickle.py", line 402, in load_build
    Unpickler.load_build(self)
  File "python3.9/pickle.py", line 1717, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 714, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1418, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Thank you very much in advance for your reply.
Sincerely.

**Comment by LinaDongXMU** [comment]
Maybe you can try to install scikit-learn ==1.0.2. And I hope this will help to deal with the error.

**Comment by mglgc** [comment]
Thanks for your reply. It works to output the results.csv file but with some warnings as follow:

python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
python3.9/site-packages/sklearn/utils/validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator ExtraTreeRegressor from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator ExtraTreesRegressor from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

**Comment by LinaDongXMU** [comment]
These warnings may come from python3.9. GXLE used python3.7 as its base environment.

**Comment by mglgc** [comment]
Thank you once more for your ready reply.

**Comment by mglgc** [comment]
> These warnings may come from python3.9. GXLE used python3.7 as its base environment.

Thank you once more for your ready reply.

**Comment by mglgc** [comment]
> 



> > These warnings may come from python3.9. GXLE used python3.7 as its base environment.
> 
> Thank you once more for your ready reply.


Anyway using python3.7 in the GXLE environment a couple of warning lines remain showing:

envs/GXLE/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator ExtraTreeRegressor from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
envs/GXLE/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator ExtraTreesRegressor from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,

**Comment by LinaDongXMU** [comment]
From the error message perspective, it is due to the high version of scikit-learn, which is not supported and needs to be downgraded to 0.24.1. Try:
pip install scikit-learn==0.24.1

**Comment by mglgc** [comment]
> From the error message perspective, it is due to the high version of scikit-learn, which is not supported and needs to be downgraded to 0.24.1. Try: pip install scikit-learn==0.24.1

It works. Thank you so much.
